backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images/uploads/"
# public_folder: "/images/uploads/"
site_url: "https://11ty-boilerplate.netlify.app/"
display_url: "https://11ty-boilerplate.netlify.app/"
# logo_url: https://your-site.com/images/logo.svg
publish_mode: editorial_workflow

collections:
  - label: "Meta Tags"
    name: "meta_tags"
    description: "Add and Edit Meta Tags"
    files:
      - label: "About Page"
        name: "about"
        file: "src/_data/meta/about.json"
        fields:
          - label: About Page Meta Tags
            name: tags
            widget: list
            fields:
              - {label: Name , name: name, widget: string}
              - {label: Content, name: content, widget: text}
      - label: "Blog Page"
        name: "blog"
        file: "src/_data/meta/blog.json"
        fields:
          - label: Blog Page Meta Tags
            name: tags
            widget: list
            fields:
              - {label: Name , name: name, widget: select}
              - {label: Content, name: content, widget: text}


  - label: "Themes"
    name: "themes"
    description: "Custom Themes"
    files:
      - label: "Theme Colors"
        name: "themes_colors"
        file: "src/_data/sass/sass-vars.json"
        fields:
          - label: "Background Colors"
            name: "bg-color"
            widget: "list"
            fields:
              - {label: "Base", name: "base", widget: "color"}
              - {label: "Primary", name: "primary", widget: "color"}
              - {label: "Secondary", name: "secondary", widget: "color"}
          - label: "Text Colors"
            name: "text-color"
            widget: "list"
            fields:
              - {label: "Base", name: "base", widget: "color"}
              - {label: "Primary", name: "primary", widget: "color"}
              - {label: "Secondary", name: "secondary", widget: "color"}