backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images/blog/"
public_folder: "/images/blog/"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Image Description", name: "imageAlt", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "meta-tags"
    label: "Meta Tags"
    description: "Add and Edit Meta Data Tags"
    create: true
    delete: true
    files:
      - label: "Home"
        name: "index"
        file: "src/_data/meta/home.json"
        fields:
          - label: "Home Page Meta Tags"
            name: "home-tags"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Content", name: "content", widget: "text"}
      

  - name: "custom"
    label: "Custom"
    description: "Custom Themes"
    files:
      - label: "themes"
        name: "Themes"
        file: "src/_data/sass/sass-vars.json"
        fields:
          - label: "Background Colors"
            name: "bg-color"
            widget: "list"
            fields:
              - {label: "Base", name: "base", widget: "color"}
              - {label: "Primary", name: "primary", widget: "color"}
              - {label: "Secondary", name: "secondary", widget: "color"}
          - label: "Text Colors"
            name: "text-color"
            widget: "list"
            fields:
              - {label: "Base", name: "base", widget: "color"}
              - {label: "Primary", name: "primary", widget: "color"}
              - {label: "Secondary", name: "secondary", widget: "color"}
      

  - name: "pages"
    label: "Pages"
    delete: true
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Over de Europeanen titel", name: about_title, widget: string}
          - {label: "Over de Europeanen content", name: about_content, widget: text}
          - {label: "Over de Europeanen meer knop titel", name: about_button_title, widget: string}
          - {label: "Nieuws titel", name: news_title, widget: string}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title hoofdkaart", name: "title", widget: "string"}
          - {label: "Body hoofdkaart", name: "body", widget: "markdown"}